apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end            
  labels:
    app: sock-shop
spec:
  replicas: 3             
  selector:
    matchLabels:
      app: sock-shop
  template:
    metadata:
      labels:
        app: sock-shop
    spec:
      containers:
      - name: front-end
        image: weaveworksdemos/front-end:0.3.12   
        ports:
        - containerPort: 8079        
        resources:
          requests:
            cpu: "250m"            
            memory: "256Mi"        
          limits:
            cpu: "500m"            
            memory: "512Mi"        
      restartPolicy: Always
