apiVersion: argoproj.io/v1alpha1 # Don't change for now
kind: Rollout
metadata:
  name: front-end
  namespace: sock-shop
  labels:
    app: front-end
spec:
  replicas: 5 # Mess with this later
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: weaveworksdemos/front-end:0.3.13 # Make a change here to test canary/argocd rollback
          ports:
            - containerPort: 8079
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
