apiVersion: argoproj.io/v1alpha1 # Don't change for now
kind: Rollout
metadata:
  name: front-end
  namespace: sock-shop
  labels:
    app: front-end
spec:
  replicas: 5 # Mess with this later
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: weaveworksdemos/front-end:0.3.12
          ports:
            - containerPort: 8079
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 20 }
        - setWeight: 50
        - pause: { duration: 20 }
        - setWeight: 100
