apiVersion: v1
kind: Rollout
metadata:
  name: front-end
  labels:
    app: front-end
spec:
  replicas: 5 # mess around with this later
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: weaveworksdemos/front-end:0.5.0  
          ports:
            - containerPort: 8079
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 20 }
        - setWeight: 50
        - pause: { duration: 20 }
        - setWeight: 100
